package com.wolfteam.pojo.wx;


import java.io.Serializable;
import java.util.Date;

public class AutoReplyConfigDTO implements Serializable{
    
	private static final long serialVersionUID = 2259378567805041636L;
	
	private Integer sortId;
	
	private String title;
	
	private String url;
	
	private String redirectUrl;
	
	private String content;
	
	public Integer getSortId() {
		return sortId;
	}

	public void setSortId(Integer sortId) {
		this.sortId = sortId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getRedirectUrl() {
		return redirectUrl;
	}

	public void setRedirectUrl(String redirectUrl) {
		this.redirectUrl = redirectUrl;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	private Integer id;
	private String keyword;
	private Integer replyType;
	private String orginId;
	private String matchType;
	private String isUse;
	private Date starttime;
	private Date endtime;
	private String unbindKeyword;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_reply_config.keyword
	 * @param keyword  the value for auto_reply_config.keyword
	 * @mbggenerated
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_reply_config.reply_type
	 * @return  the value of auto_reply_config.reply_type
	 * @mbggenerated
	 */
	public Integer getReplyType() {
		return replyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_reply_config.reply_type
	 * @param replyType  the value for auto_reply_config.reply_type
	 * @mbggenerated
	 */
	public void setReplyType(Integer replyType) {
		this.replyType = replyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_reply_config.orgin_id
	 * @return  the value of auto_reply_config.orgin_id
	 * @mbggenerated
	 */
	public String getOrginId() {
		return orginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_reply_config.orgin_id
	 * @param orginId  the value for auto_reply_config.orgin_id
	 * @mbggenerated
	 */
	public void setOrginId(String orginId) {
		this.orginId = orginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_reply_config.match_type
	 * @return  the value of auto_reply_config.match_type
	 * @mbggenerated
	 */
	public String getMatchType() {
		return matchType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_reply_config.match_type
	 * @param matchType  the value for auto_reply_config.match_type
	 * @mbggenerated
	 */
	public void setMatchType(String matchType) {
		this.matchType = matchType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_reply_config.is_use
	 * @return  the value of auto_reply_config.is_use
	 * @mbggenerated
	 */
	public String getIsUse() {
		return isUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_reply_config.is_use
	 * @param isUse  the value for auto_reply_config.is_use
	 * @mbggenerated
	 */
	public void setIsUse(String isUse) {
		this.isUse = isUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_reply_config.starttime
	 * @return  the value of auto_reply_config.starttime
	 * @mbggenerated
	 */
	public Date getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_reply_config.starttime
	 * @param starttime  the value for auto_reply_config.starttime
	 * @mbggenerated
	 */
	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_reply_config.endtime
	 * @return  the value of auto_reply_config.endtime
	 * @mbggenerated
	 */
	public Date getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_reply_config.endtime
	 * @param endtime  the value for auto_reply_config.endtime
	 * @mbggenerated
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_reply_config.unbind_keyword
	 * @return  the value of auto_reply_config.unbind_keyword
	 * @mbggenerated
	 */
	public String getUnbindKeyword() {
		return unbindKeyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_reply_config.unbind_keyword
	 * @param unbindKeyword  the value for auto_reply_config.unbind_keyword
	 * @mbggenerated
	 */
	public void setUnbindKeyword(String unbindKeyword) {
		this.unbindKeyword = unbindKeyword;
	}
}
